version: '3'

services:

    search-api:
        build: .
        command: sh -c "fastapi run app/main.py"
        ports:
            - "9000:8000" 
    bot:
      build: .
      env_file:
        - .env
      restart: always
      command: sh -c "python app/bot/bot.py"
      depends_on:
          - search-api